### ISSUE TITLE
CodeQL Scan Autobuild step fails when we use an internal nuget package (github package)

### ISSUE THREAD

**Issue by nedimhadz** [coopnorge/github-workflow-supply-chain-security-validation#63]
dotnet restore is failing because it does not know about the coop nuget packages. We need a way to add coopnorge nuget as a package source so that it will be able to build.
![image](https://github.com/coopnorge/github-workflow-supply-chain-security-validation/assets/47382010/12b12632-22ed-40b0-8c2b-47d6470db16d)

Similarly like we do here in our own build where dotnet restore works:
https://github.com/coopnorge/fruktklient/blob/rewrite-to-use-messaging-from-nugetpackage/.github/workflows/pr.yaml#L39

**Comment by nhhagen** [comment]
Is there a way to provide a local nuget configuration as a file?

**Comment by nedimhadz** [comment]
@nhhagen are you sure that nuget.config can be used with GITHUB_TOKEN? As far as i can read it only supports personal access token. I've now tried to add a nuget.config file, but have not figured out how to provide it the correct credentials

**Comment by nhhagen** [comment]
we still need to solve the credentials part.

When this workflow was developed we had no internal packages.

**Comment by nedimhadz** [comment]
@nhhagen Is there any way we could have done a "setup dotnet" in the codeql action, similarly as we do setup go and setup java. And then in that step add the coopnorge github package source?

**Comment by nedimhadz** [comment]
we want to use this way of adding the nuget source instead of nuget.config with personal access token:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-in-a-github-actions-workflow

I might be wrong here, maybe they can be used together (nuget.config but with github_token), just dont know how

**Comment by nedimhadz** [comment]
![image](https://github.com/coopnorge/github-workflow-supply-chain-security-validation/assets/47382010/6d3d262b-df94-4168-882e-45cc3ad0ebf6)

could something like this work? Maybe with a condition around stating it should only run for dotnet or c# lang

**Comment by nhhagen** [comment]
sure, I suggest you create the PR to implement this.

**Comment by nedimhadz** [comment]
https://github.com/coopnorge/github-workflow-supply-chain-security-validation/pull/64

**Comment by nhhagen** [comment]
@nedimhadz you could have referenced the branch i a PR in one of your repos.

**Comment by nhhagen** [comment]
Fixed by: #64
