### ISSUE TITLE
Trivy and Dependabot are both creating security alerts thus causing duplicate alerts

### ISSUE THREAD

**Issue by AtzeDeVries** [coopnorge/github-workflow-supply-chain-security-validation#90]
Trivy and Dependabot are both creating security alerts thus causing duplicate alerts. Would be nice to get rid of the dups. 

cc: @nhhagen

**Comment by pravindahal** [comment]
Could be tried by duplicating a project with known vulnerabilities.

**Comment by pravindahal** [comment]
There is also another issue that has been introduced because of added misconfig scanner. Now, it complains on the docker files. We need a default ignore configuration which ignores these issues.

**Comment by pravindahal** [comment]
The issues have been fixed.
